"""Instrument (harness) version boundary for real-model measurements.

Phase B established that the pre-repair native-tools path lost the tool
contract from the *rendered* prompt on every model call after the first for
providers whose chat template renders tool definitions only adjacent to the
final user turn.  Runs produced before that repair and runs produced after it
were therefore generated by materially different instruments, even though the
benchmark, policy, prompts, and metric definitions are byte-identical.

``INSTRUMENT_VERSION`` exists so that this boundary is machine-checkable rather
than a footnote.  It is recorded in every experiment manifest and every raw
row, and pooled analysis refuses to merge sources that disagree on it.

Analytic rule (enforced in ``iqa_soa.metrics.pilot``):

    Measurements carrying different ``instrument_version`` values MUST NOT be
    merged, pooled, averaged, or compared as though they were generated under
    identical instrumentation.

This module deliberately contains no logic beyond the constants, so that
importing it can never fail or introduce a cycle.
"""

from __future__ import annotations

# Pre-repair instrument: Stage-1, Stage-2, and Phase-A measurements.  Manifests
# and rows written before the Class-P repair carry no explicit field, so
# readers default to this value.
PRE_REPAIR_INSTRUMENT_VERSION = "1"

# Post-repair instrument: tool-contract persistence, multi-tool-call handling,
# terminal-no-action telemetry, and provider runtime provenance.
INSTRUMENT_VERSION = "2"

# Identifies the native-tools request/response adapter specifically, so a later
# adapter change is distinguishable from an unrelated instrument change.
NATIVE_TOOL_ADAPTER_VERSION = "native-tools-adapter-2"

# Raw-row schema written by the post-repair instrument.  Schema 2 remains the
# readable contract for frozen pre-repair artifacts.
PRE_REPAIR_RAW_SCHEMA_VERSION = 2
RAW_SCHEMA_VERSION = 3


__all__ = [
    "INSTRUMENT_VERSION",
    "NATIVE_TOOL_ADAPTER_VERSION",
    "PRE_REPAIR_INSTRUMENT_VERSION",
    "PRE_REPAIR_RAW_SCHEMA_VERSION",
    "RAW_SCHEMA_VERSION",
]
