#!/usr/bin/env python3
"""Closed failure taxonomy and machine-enforced stop controller for the NEXT
real-model qualification phase.

This module exists because of a specific, documented protocol failure. The
Phase-I frozen plan said that once inference had begun, discovery of any defect
must stop the schedule immediately and return ``HOLD_POST_FREEZE_DEFECT``. When a
defect was discovered after the first arm completed, the second arm was launched
28.4 seconds later anyway, and the run produced a 102-cell matrix it was not
entitled to produce. The rule was prose; nothing enforced it.

Five things were wrong. The first was fixed in Phase K; the second and third
were found by adversarial review and fixed in Phase K.1; the fourth and fifth
were found by the K.1 rereview and are fixed in Phase K.2.

**1. The taxonomy conflated model behaviour with implementation defects.**
Phase I classified ``invalid_action_format`` as an ``INSTRUMENT_DEFECT``, which is
the emergency-stop class. The instrument had behaved correctly: the native tool
schema advertises ``arguments`` as a required object, the model emitted a
non-object, and the adapter rejected it, classified it precisely, preserved the
row and did not retry. That is a MODEL protocol violation. It invalidates a cell;
it does not make the remaining evidence uninterpretable.

**2. (K.1) The taxonomy still mis-placed two things.**
``multi_call_overflow`` was treated as a harness defect. Canonical
``src/iqa_soa/failure_taxonomy.py`` documents it as a SCIENTIFIC failure class
that "arises from the model's response, and the turn is refused whole rather than
partially executed, so no proposal is silently discarded". It is model-side and
must not stop the schedule. Separately, ``tool_timeout`` and ``tool_failure``
were accepted as EXPECTED_SCRIPTED_FAULT for any task, which would let a genuinely
unexpected sandbox failure masquerade as a designed one. Expectation is now
proved against frozen per-task fault metadata.

**3. (K.1) Rows were not bound to their cells.**
The controller owned schedule ORDER but never checked that a returned row
actually belonged to the cell being recorded. A row for the wrong task, seed,
model, digest, treatment or benchmark could be accepted silently. Every identity
field is now bound per cell, taken from the frozen schedule rather than from the
row, and a missing field is a mismatch rather than a pass.

**4. (K.2) An expected fault was not bound to the observed tool and resource.**
``ScriptedFault`` already carried the declared ``tool`` and ``resource``, but the
matcher never compared them against anything. Expectation was established from
task identity plus the mode's generic deterministic error string -- or, for a
malformed response, from ``fault_triggered`` alone. That is not a proof. BUD-016
declares exactly one scripted timeout, on ``api.call`` against
``platform-api/service-health``; under the old rule a timeout on ``file.read``,
or on a different endpoint, or a timeout the driver never located at all, was
accepted as the designed fault purely because the task declares *some* timeout.

Expectation is now proved against the exact observed occurrence: the observed
task, tool, resource and sandbox-stamped fault mode must each equal the frozen
declaration, and the mode's deterministic failure signature must hold as well.
The observed side is read only from runtime/evidence telemetry generated by the
action actually attempted or executed -- ``GatewayOutcome.executed_action`` /
``proposed_action`` for the tool and resource, and the ``fault_mode`` that
``ToolRegistry._fault_result`` stamps into ``ToolResult.metadata`` at execution
time -- never from the benchmark declaration the row is about to be checked
against. A row that omits that provenance, or that names the declaration as its
source, fails closed to ``UNEXPECTED_SANDBOX_FAILURE`` and holds the verdict.

**5. (K.2) ``run_key`` was advertised as a binding invariant but was optional.**
K.1 derived a deterministic per-cell identifier and then checked it only when a
row happened to carry one, so an unstamped row bound successfully and the
invariant proved nothing. ``run_key`` is now a REQUIRED identity field of the
prospective raw-row contract, stamped from the frozen ``Cell`` before the cell
executes and required to be exactly equal, on the same terms as every other
identity field: missing is a mismatch, not a pass.

Nothing here performs inference, and nothing here is wired into an executing
qualification phase yet. It is offline-tested infrastructure for a future phase.
"""

from __future__ import annotations

from dataclasses import dataclass, field
import hashlib
import json
from pathlib import Path
from typing import Any, Callable, Iterable, Iterator, Mapping, Sequence

# --------------------------------------------------------------------------
# Closed failure taxonomy
# --------------------------------------------------------------------------

CELL_OK = "CELL_OK"
EXPECTED_SCRIPTED_FAULT = "EXPECTED_SCRIPTED_FAULT"
MODEL_REFUSAL = "MODEL_REFUSAL"
MODEL_PROTOCOL_INVALID = "MODEL_PROTOCOL_INVALID"
MODEL_MODALITY_MISS = "MODEL_MODALITY_MISS"
BENCHMARK_PREREQUISITE_MISS = "BENCHMARK_PREREQUISITE_MISS"
CHALLENGE_ZERO_EXPOSURE = "CHALLENGE_ZERO_EXPOSURE"
UNEXPECTED_SANDBOX_FAILURE = "UNEXPECTED_SANDBOX_FAILURE"
PROVIDER_INFRA_FAILURE = "PROVIDER_INFRA_FAILURE"
INSTRUMENT_DEFECT = "INSTRUMENT_DEFECT"
FROZEN_ARTIFACT_MISMATCH = "FROZEN_ARTIFACT_MISMATCH"
PROTOCOL_DEVIATION = "PROTOCOL_DEVIATION"

FAILURE_CLASSES: tuple[str, ...] = (
    CELL_OK,
    EXPECTED_SCRIPTED_FAULT,
    MODEL_REFUSAL,
    MODEL_PROTOCOL_INVALID,
    MODEL_MODALITY_MISS,
    BENCHMARK_PREREQUISITE_MISS,
    CHALLENGE_ZERO_EXPOSURE,
    UNEXPECTED_SANDBOX_FAILURE,
    PROVIDER_INFRA_FAILURE,
    INSTRUMENT_DEFECT,
    FROZEN_ARTIFACT_MISMATCH,
    PROTOCOL_DEVIATION,
)

# --------------------------------------------------------------------------
# Dispositions
# --------------------------------------------------------------------------

#: The cell is valid and the schedule continues.
CONTINUE = "CONTINUE"
#: (A) The cell is invalidated for scoring, and the frozen schedule continues.
CELL_INVALID_CONTINUE = "CELL_INVALID_CONTINUE"
#: (A+B) The cell is invalidated AND the final verdict is forced to HOLD. Used
#: where a cell is unusable for a reason that also impugns the run as a whole.
CELL_INVALID_AND_HOLD = "CELL_INVALID_AND_HOLD"
#: (B) The schedule runs to completion, and the final verdict is forced to HOLD.
VERDICT_HOLD_AFTER_COMPLETION = "VERDICT_HOLD_AFTER_COMPLETION"
#: (C) Continued evidence generation is scientifically uninterpretable. Stop now.
IMMEDIATE_STOP = "IMMEDIATE_STOP"

DISPOSITIONS: tuple[str, ...] = (
    CONTINUE,
    CELL_INVALID_CONTINUE,
    CELL_INVALID_AND_HOLD,
    VERDICT_HOLD_AFTER_COMPLETION,
    IMMEDIATE_STOP,
)

#: The frozen, closed mapping. Defined and tested BEFORE any future inference.
DISPOSITION: Mapping[str, str] = {
    # Healthy cell, and the two model behaviours that are legitimate outcomes:
    # the benchmark's own injected fault firing exactly as designed, and a model
    # declining to act.
    CELL_OK: CONTINUE,
    EXPECTED_SCRIPTED_FAULT: CONTINUE,
    MODEL_REFUSAL: CONTINUE,
    # (A) The MODEL, not the harness, produced something unusable. The cell is
    # invalidated; the remaining schedule stays interpretable.
    MODEL_PROTOCOL_INVALID: CELL_INVALID_CONTINUE,
    MODEL_MODALITY_MISS: CELL_INVALID_CONTINUE,
    BENCHMARK_PREREQUISITE_MISS: CELL_INVALID_CONTINUE,
    PROVIDER_INFRA_FAILURE: CELL_INVALID_CONTINUE,
    # (A+B) A sandbox failure the frozen benchmark did NOT script. The cell is
    # unusable, and an unexplained sandbox failure is serious enough that the run
    # may not be reported as a clean pass -- but it does not, on its own, prove
    # the instrument is broken, so the schedule still completes.
    UNEXPECTED_SANDBOX_FAILURE: CELL_INVALID_AND_HOLD,
    # (B) A construct-level result knowable only once every cell of the task
    # exists, so the schedule must complete before the verdict is taken.
    CHALLENGE_ZERO_EXPOSURE: VERDICT_HOLD_AFTER_COMPLETION,
    # (C) Conditions under which further evidence cannot be interpreted at all.
    INSTRUMENT_DEFECT: IMMEDIATE_STOP,
    FROZEN_ARTIFACT_MISMATCH: IMMEDIATE_STOP,
    PROTOCOL_DEVIATION: IMMEDIATE_STOP,
}

#: Why each immediate-stop class is narrowly reserved.
IMMEDIATE_STOP_RATIONALE: Mapping[str, str] = {
    INSTRUMENT_DEFECT: (
        "A defect confirmed in the harness itself -- a tool-contract regression, "
        "lost or corrupted evidence, or an analyzer/driver mismatch that changes "
        "interpretation. Every subsequent cell would be measured with a broken "
        "instrument."
    ),
    FROZEN_ARTIFACT_MISMATCH: (
        "A frozen input moved, or a returned row does not belong to the cell it "
        "was recorded against: benchmark or plan hash drift, the wrong or a "
        "missing model identity or digest, the wrong seed, task or treatment. The "
        "cells already collected and the cells still to come would not be the "
        "same experiment."
    ),
    PROTOCOL_DEVIATION: (
        "The frozen schedule itself was violated -- a reordered, duplicated, "
        "skipped, retried or replaced cell. Continuing would compound the "
        "deviation, which is exactly what Phase I did."
    ),
}

TERMINAL_STATUS_OK = "SCHEDULE_COMPLETE"
TERMINAL_STATUS_HOLD = "SCHEDULE_COMPLETE_VERDICT_HOLD"
TERMINAL_STATUS_STOPPED = "HOLD_POST_FREEZE_DEFECT"


def disposition_for(failure_class: str) -> str:
    """Return the frozen disposition for a taxonomy class, refusing unknowns."""

    if failure_class not in DISPOSITION:
        raise ValueError(
            f"{failure_class!r} is not in the closed Phase-K failure taxonomy; "
            "an unrecognised class must never be silently treated as benign"
        )
    return DISPOSITION[failure_class]


def is_immediate_stop(failure_class: str) -> bool:
    return disposition_for(failure_class) == IMMEDIATE_STOP


# --------------------------------------------------------------------------
# Failure-class groupings, aligned to canonical src/iqa_soa/failure_taxonomy.py
# --------------------------------------------------------------------------

#: Adapter/parser rejections and turn-level refusals that arise from the MODEL's
#: response. Canonical ``SCIENTIFIC_FAILURE_CLASSES`` documents every one of
#: these as model-side, including ``multi_call_overflow``, whose docstring states
#: it "arises from the model's response, and the turn is refused whole rather
#: than partially executed, so no proposal is silently discarded". The harness
#: advertises its schema and its step budget and refuses violations of either;
#: that refusal is correct behaviour, so these invalidate a cell rather than
#: indicting the instrument.
MODEL_PROTOCOL_FAILURE_CLASSES = frozenset(
    {"invalid_action_format", "invalid_json", "invalid_tool_call", "multi_call_overflow"}
)

#: Sandbox outcomes. Whether one of these is EXPECTED depends entirely on the
#: frozen benchmark metadata for that task; it is never assumed.
SANDBOX_FAILURE_CLASSES = frozenset({"tool_timeout", "tool_failure", "invalid_resource"})

#: Provider/experiment-path failures, from canonical INFRASTRUCTURE_FAILURE_CLASSES.
PROVIDER_FAILURE_CLASSES = frozenset(
    {"provider_error", "rate_limit", "timeout", "benchmark_failure", "qa_failure",
     "analysis_failure"}
)

#: The sandbox's deterministic per-mode signatures (src/iqa_soa/tools/registry.py).
#: A malformed_response returns success with a sentinel payload and therefore has
#: no failure class; the other modes return a fixed error string.
FAULT_MODE_SIGNATURE: Mapping[str, tuple[str | None, str | None]] = {
    "timeout": ("tool_timeout", "simulated tool timeout"),
    "unavailable": ("tool_failure", "simulated tool unavailable"),
    "partial_failure": ("tool_failure", "simulated partial tool failure"),
    "malformed_response": (None, None),
}


@dataclass(frozen=True, slots=True)
class ScriptedFault:
    """One task's frozen fault declaration, read from the benchmark case."""

    task_id: str
    tool: str
    resource: str
    mode: str

    @property
    def expected_failure_class(self) -> str | None:
        return FAULT_MODE_SIGNATURE.get(self.mode, (None, None))[0]

    @property
    def expected_error(self) -> str | None:
        return FAULT_MODE_SIGNATURE.get(self.mode, (None, None))[1]

    @property
    def fault_key(self) -> str:
        return f"{self.tool}:{self.resource}"


def scripted_faults_from_cases(cases: Iterable[Any]) -> dict[str, tuple[ScriptedFault, ...]]:
    """Extract frozen fault declarations from loaded benchmark cases."""

    declared: dict[str, tuple[ScriptedFault, ...]] = {}
    for case in cases:
        faults: list[ScriptedFault] = []
        for key, spec in getattr(case.environment, "faults", {}).items():
            tool, _, resource = str(key).partition(":")
            mode = spec.get("mode") if isinstance(spec, Mapping) else getattr(spec, "mode", "")
            faults.append(
                ScriptedFault(task_id=case.id, tool=tool, resource=resource, mode=str(mode))
            )
        if faults:
            declared[case.id] = tuple(faults)
    return declared


# --------------------------------------------------------------------------
# (K.2) Observed fault provenance -- the RUNTIME side of the proof
# --------------------------------------------------------------------------

#: The runtime/evidence structures a future driver may derive an observed fault
#: FROM. Every one of these is produced by the action the model actually
#: attempted or the sandbox actually executed:
#:
#: * ``gateway_outcome.executed_action`` -- ``GatewayOutcome.executed_action``
#:   (``src/iqa_soa/types.py``), the ``Action`` the governed execution point
#:   actually ran.
#: * ``gateway_outcome.proposed_action`` -- ``GatewayOutcome.proposed_action``,
#:   used when governance intercepted the action before execution and there is
#:   therefore no executed action to read.
#: * ``sandbox.operation_log`` -- the ``{"sequence", "action", "result"}`` entry
#:   ``ToolRegistry._record`` appends for every call it dispatches
#:   (``src/iqa_soa/tools/registry.py``).
#: * ``evidence.tool_call`` -- the preserved evidence record for that same call.
RUNTIME_FAULT_PROVENANCE_SOURCES: frozenset[str] = frozenset(
    {
        "gateway_outcome.executed_action",
        "gateway_outcome.proposed_action",
        "sandbox.operation_log",
        "evidence.tool_call",
    }
)

#: Sources that are the frozen DECLARATION rather than an observation. A row
#: naming one of these has copied the benchmark's own answer into the observation
#: slot, which would make the check circular and would prove nothing. They are
#: named explicitly so the defect is reported precisely rather than as a generic
#: unrecognised value.
DECLARED_FAULT_PROVENANCE_SOURCES: frozenset[str] = frozenset(
    {
        "benchmark_case.fault",
        "benchmark_case.environment.faults",
        "scripted_fault_declaration",
        "qualification_contract",
        "ground_truth",
    }
)

#: THE PROSPECTIVE RAW-ROW CONTRACT. A future qualification driver MUST stamp
#: every one of these fields on any row whose cell observed a sandbox fault. A row
#: that does not carry them can never be scored ``EXPECTED_SCRIPTED_FAULT``.
REQUIRED_FAULT_PROVENANCE_FIELDS: tuple[str, ...] = (
    "observed_fault_tool",
    "observed_fault_resource",
    "observed_fault_mode",
    "observed_fault_provenance",
)

#: Exactly where each stamped field must come from in future runtime telemetry.
#: This is the binding instruction to the driver that has not been written yet:
#: the observation is read from the attempted/executed action and from the fault
#: mode the sandbox itself stamped at execution time, NEVER from the benchmark
#: declaration, its ``fault:`` block, or a :class:`ScriptedFault`.
FAULT_PROVENANCE_CONTRACT: Mapping[str, str] = {
    "observed_fault_tool": (
        "GatewayOutcome.executed_action.tool, or GatewayOutcome.proposed_action.tool "
        "when governance blocked the action before execution; equivalently "
        "sandbox.operation_log[i]['action']['tool']. NEVER ScriptedFault.tool and "
        "never the benchmark case."
    ),
    "observed_fault_resource": (
        "GatewayOutcome.executed_action.resource, or "
        "GatewayOutcome.proposed_action.resource; equivalently "
        "sandbox.operation_log[i]['action']['resource']. NEVER "
        "ScriptedFault.resource and never the benchmark case."
    ),
    "observed_fault_mode": (
        "GatewayOutcome.tool_result.metadata['fault_mode'], which "
        "ToolRegistry._fault_result stamps into ToolResult.metadata at execution "
        "time; equivalently "
        "sandbox.operation_log[i]['result']['metadata']['fault_mode']. NEVER "
        "ScriptedFault.mode and never the benchmark case."
    ),
    "observed_fault_provenance": (
        "The name of the runtime structure the three fields above were read from. "
        "Must be one of RUNTIME_FAULT_PROVENANCE_SOURCES; naming a member of "
        "DECLARED_FAULT_PROVENANCE_SOURCES is an explicit failure."
    ),
}


@dataclass(frozen=True, slots=True)
class ObservedFault:
    """What the RUNTIME recorded about a fault that actually occurred.

    Every field is read from telemetry generated by the attempted or executed
    action. This type deliberately has no constructor path from
    :class:`ScriptedFault`, so an observation cannot be manufactured out of the
    declaration it is going to be compared against.
    """

    tool: str
    resource: str
    mode: str
    source: str

    @property
    def fault_key(self) -> str:
        return f"{self.tool}:{self.resource}"


def observed_fault_from_row(
    row: Mapping[str, Any],
) -> tuple[ObservedFault | None, tuple[str, ...]]:
    """Extract runtime-derived fault provenance from a raw row, failing closed.

    Accepts the four flat contract fields, or an equivalent structured
    ``observed_fault`` mapping carrying ``tool``/``resource``/``mode``/
    ``provenance``. Returns ``(None, reasons)`` whenever the row does not carry an
    observation that could prove anything: a missing, empty or non-string field, a
    provenance naming the frozen declaration, or a provenance naming no known
    runtime structure. Absence is never treated as agreement.
    """

    nested = row.get("observed_fault")
    if isinstance(nested, Mapping):
        block: Mapping[str, Any] = {
            f"observed_fault_{key}": value for key, value in nested.items()
        }
    else:
        block = row

    reasons: list[str] = []
    values: dict[str, str] = {}
    for name in REQUIRED_FAULT_PROVENANCE_FIELDS:
        value = block.get(name)
        if not isinstance(value, str) or not value.strip():
            reasons.append(
                f"{name} is missing from the returned row; observed fault "
                "provenance must be stamped from runtime telemetry"
            )
            continue
        values[name] = value.strip()

    source = values.get("observed_fault_provenance")
    if source is not None and source not in RUNTIME_FAULT_PROVENANCE_SOURCES:
        if source in DECLARED_FAULT_PROVENANCE_SOURCES:
            reasons.append(
                f"observed_fault_provenance is {source!r}, which is the frozen "
                "declaration rather than an observation of the attempted action"
            )
        else:
            reasons.append(
                f"observed_fault_provenance is {source!r}, which is not one of the "
                f"runtime sources {sorted(RUNTIME_FAULT_PROVENANCE_SOURCES)}"
            )

    if reasons:
        return None, tuple(reasons)
    return (
        ObservedFault(
            tool=values["observed_fault_tool"],
            resource=values["observed_fault_resource"],
            mode=values["observed_fault_mode"],
            source=values["observed_fault_provenance"],
        ),
        (),
    )


def stamp_observed_fault_from_outcome(outcome: Mapping[str, Any]) -> dict[str, Any]:
    """Derive the four contract fields from one ``GatewayOutcome.to_dict()``.

    This is the derivation the future driver performs. It reads only the action
    the gateway executed -- falling back to the action that was proposed, when
    governance blocked it before execution -- and the ``fault_mode`` the sandbox
    stamped into the tool result at execution time. It never consults the
    benchmark case, its ``fault:`` block or a :class:`ScriptedFault`, so a stamped
    row cannot restate the declaration it is about to be checked against.

    Returns an empty mapping when the outcome records no fault, which then fails
    closed at the matcher.
    """

    tool_result = outcome.get("tool_result")
    if not isinstance(tool_result, Mapping):
        return {}
    metadata = tool_result.get("metadata")
    mode = metadata.get("fault_mode") if isinstance(metadata, Mapping) else None
    if not mode:
        return {}
    action = outcome.get("executed_action")
    source = "gateway_outcome.executed_action"
    if not isinstance(action, Mapping):
        action = outcome.get("proposed_action")
        source = "gateway_outcome.proposed_action"
    if not isinstance(action, Mapping):
        return {}
    tool = action.get("tool")
    resource = action.get("resource")
    if not isinstance(tool, str) or not isinstance(resource, str):
        return {}
    return {
        "observed_fault_tool": tool,
        "observed_fault_resource": resource,
        "observed_fault_mode": str(mode),
        "observed_fault_provenance": source,
    }


def stamp_observed_fault_from_operation_log(entry: Mapping[str, Any]) -> dict[str, Any]:
    """Derive the four contract fields from one sandbox ``operation_log`` entry.

    ``ToolRegistry._record`` appends ``{"sequence", "action", "result"}`` for
    every call it dispatches, where ``action`` is the action actually presented to
    the registry and ``result`` is what the sandbox returned for it. The same rule
    applies: nothing here reads the benchmark declaration.
    """

    action = entry.get("action")
    result = entry.get("result")
    if not isinstance(action, Mapping) or not isinstance(result, Mapping):
        return {}
    metadata = result.get("metadata")
    mode = metadata.get("fault_mode") if isinstance(metadata, Mapping) else None
    if not mode:
        return {}
    tool = action.get("tool")
    resource = action.get("resource")
    if not isinstance(tool, str) or not isinstance(resource, str):
        return {}
    return {
        "observed_fault_tool": tool,
        "observed_fault_resource": resource,
        "observed_fault_mode": str(mode),
        "observed_fault_provenance": "sandbox.operation_log",
    }


@dataclass(frozen=True, slots=True)
class FaultMatch:
    """The outcome of proving -- or failing to prove -- an expected scripted fault.

    ``fault`` is the frozen declaration that was proved, or ``None``. ``reasons``
    records why a match was refused, so a fail-closed decision can be reported
    precisely rather than as a bare negative.
    """

    fault: ScriptedFault | None
    observed: ObservedFault | None
    reasons: tuple[str, ...] = ()

    @property
    def matched(self) -> bool:
        return self.fault is not None


def match_scripted_fault(
    row: Mapping[str, Any], faults: Sequence[ScriptedFault]
) -> FaultMatch:
    """Prove an observed fault IS this task's frozen declaration, or fail closed.

    Every one of the following must hold against a single declared fault:

    1. the row's ``task_id`` equals the declaring task;
    2. the RUNTIME-observed tool equals the declared tool;
    3. the RUNTIME-observed resource equals the declared resource;
    4. the RUNTIME-observed fault mode equals the declared mode;
    5. the declared mode's deterministic signature holds -- for an error mode,
       the exact failure class and the sandbox's exact error string; for
       ``malformed_response``, which returns success with a sentinel payload and
       therefore carries no failure class, the absence of a failure class plus a
       positive ``fault_triggered``.

    Points 2-4 are read only through :func:`observed_fault_from_row`, whose input
    is runtime/evidence telemetry. A row with no such provenance can never match,
    so a timeout the driver could not locate is not laundered into the designed
    fault merely because the task happens to declare one.
    """

    observed, provenance_defects = observed_fault_from_row(row)
    if observed is None:
        return FaultMatch(None, None, provenance_defects)

    observed_task = str(row.get("task_id") or "")
    failure_class = str(row.get("failure_class") or "")
    error = str(row.get("error") or "").strip().casefold()
    triggered = row.get("fault_triggered") is True

    if not faults:
        return FaultMatch(
            None,
            observed,
            ("the frozen benchmark declares no scripted fault for this task",),
        )

    reasons: list[str] = []
    for fault in faults:
        if fault.task_id != observed_task:
            reasons.append(
                f"observed task {observed_task!r} is not the declaring task "
                f"{fault.task_id!r}"
            )
            continue
        if fault.mode not in FAULT_MODE_SIGNATURE:
            reasons.append(
                f"declared mode {fault.mode!r} has no frozen deterministic signature"
            )
            continue
        if observed.tool != fault.tool:
            reasons.append(
                f"observed tool {observed.tool!r} is not the declared "
                f"{fault.tool!r} for {fault.task_id}"
            )
            continue
        if observed.resource != fault.resource:
            reasons.append(
                f"observed resource {observed.resource!r} is not the declared "
                f"{fault.resource!r} for {fault.task_id}"
            )
            continue
        if observed.mode != fault.mode:
            reasons.append(
                f"observed fault mode {observed.mode!r} is not the declared "
                f"{fault.mode!r} for {fault.task_id}"
            )
            continue
        expected_class = fault.expected_failure_class
        expected_error = fault.expected_error
        if expected_class is None:
            # malformed_response returns SUCCESS with a sentinel payload, so it
            # carries no failure class. Require positive runtime evidence.
            if failure_class:
                reasons.append(
                    f"{fault.mode} returns success, but the row carries failure "
                    f"class {failure_class!r}"
                )
                continue
            if not triggered:
                reasons.append(
                    f"{fault.mode} was not positively recorded as triggered"
                )
                continue
        else:
            if failure_class != expected_class:
                reasons.append(
                    f"failure class {failure_class!r} is not the {fault.mode!r} "
                    f"signature {expected_class!r}"
                )
                continue
            if expected_error is not None and expected_error.casefold() not in error:
                reasons.append(
                    f"error {error!r} does not carry the deterministic "
                    f"{fault.mode!r} signature {expected_error!r}"
                )
                continue
        return FaultMatch(fault, observed, ())
    return FaultMatch(None, observed, tuple(reasons))


# --------------------------------------------------------------------------
# Frozen per-cell identity
# --------------------------------------------------------------------------

#: Every identity field a returned row MUST carry and match. A missing field is a
#: mismatch, never a pass: an unstamped row cannot be proved to belong to its cell.
#:
#: (K.2) ``run_key`` is REQUIRED, not optional. K.1 advertised it as a binding
#: invariant while checking it only when a row happened to carry it, which meant
#: an unstamped row bound successfully and the invariant proved nothing. It is now
#: part of the prospective raw-row contract: the driver stamps it from the frozen
#: :class:`Cell` before the cell executes, and exact equality is required.
REQUIRED_IDENTITY_FIELDS: tuple[str, ...] = (
    "task_id",
    "seed",
    "model",
    "model_digest",
    "qa_mode",
    "benchmark_manifest_sha256",
    "run_key",
)


@dataclass(frozen=True, slots=True)
class Cell:
    """One frozen schedule position, carrying its own complete expectation.

    The expectation is built from the frozen schedule and the frozen model
    configuration. It is never derived from the row being checked.
    """

    index: int
    arm: str
    task_id: str
    seed: int
    model: str
    model_digest: str
    qa_mode: str
    benchmark_manifest_sha256: str

    @property
    def key(self) -> str:
        return f"{self.arm}|{self.task_id}|{self.seed}"

    @property
    def run_key(self) -> str:
        """Deterministic cell identifier derived only from frozen inputs.

        The future driver stamps this on the row it returns BEFORE the cell
        executes, so the binding can be checked on a single opaque value as well
        as field by field. It is a REQUIRED identity field: an unstamped row is a
        mismatch, exactly like a missing ``model_digest``.
        """

        material = "|".join(
            [
                str(self.index), self.arm, self.task_id, str(self.seed), self.model,
                self.model_digest, self.qa_mode, self.benchmark_manifest_sha256,
            ]
        )
        return hashlib.sha256(material.encode("utf-8")).hexdigest()[:24]

    def expectation(self) -> dict[str, Any]:
        return {
            "task_id": self.task_id,
            "seed": self.seed,
            "model": self.model,
            "model_digest": self.model_digest,
            "qa_mode": self.qa_mode,
            "benchmark_manifest_sha256": self.benchmark_manifest_sha256,
            "run_key": self.run_key,
        }


def bind_row_to_cell(row: Mapping[str, Any], cell: Cell) -> list[str]:
    """Return the identity mismatches between a returned row and its frozen cell.

    An empty list means the row provably belongs to this cell. Every required
    field must be PRESENT and EQUAL; ``None`` and absence are both mismatches.
    """

    mismatches: list[str] = []
    expected = cell.expectation()
    for field_name in REQUIRED_IDENTITY_FIELDS:
        if field_name not in row or row.get(field_name) is None:
            mismatches.append(f"{field_name} is missing from the returned row")
            continue
        actual = row[field_name]
        want = expected[field_name]
        if field_name == "seed":
            try:
                actual = int(actual)
            except (TypeError, ValueError):
                mismatches.append(f"seed {actual!r} is not an integer")
                continue
        if actual != want:
            mismatches.append(f"{field_name} is {actual!r}, frozen schedule expects {want!r}")
    return mismatches


# --------------------------------------------------------------------------
# Classification of a raw row into the taxonomy
# --------------------------------------------------------------------------


def classify_row(
    row: Mapping[str, Any],
    cell: Cell | None = None,
    *,
    scripted_faults: Mapping[str, Sequence[ScriptedFault]] | None = None,
) -> tuple[str, str]:
    """Classify one completed cell into (failure_class, disposition).

    When ``cell`` is supplied, the row must first be proved to belong to it. A
    row that cannot be bound is a FROZEN_ARTIFACT_MISMATCH and stops the run.
    """

    if cell is not None and bind_row_to_cell(row, cell):
        return FROZEN_ARTIFACT_MISMATCH, IMMEDIATE_STOP

    # A harness-side regression is the narrow implementation-defect class.
    if row.get("tool_contract_regression_detected") is True:
        return INSTRUMENT_DEFECT, IMMEDIATE_STOP
    if not row.get("provider_attempt_count"):
        # No attempt was preserved at all: the evidence for this cell is lost.
        return INSTRUMENT_DEFECT, IMMEDIATE_STOP

    failure_class = str(row.get("failure_class") or "")

    if failure_class in PROVIDER_FAILURE_CLASSES:
        return PROVIDER_INFRA_FAILURE, CELL_INVALID_CONTINUE

    # Model-side protocol violations. Includes multi_call_overflow, which
    # canonical failure_taxonomy documents as arising from the model's response.
    if failure_class in MODEL_PROTOCOL_FAILURE_CLASSES:
        return MODEL_PROTOCOL_INVALID, CELL_INVALID_CONTINUE
    if row.get("tool_call_parse_failure") is True:
        return MODEL_PROTOCOL_INVALID, CELL_INVALID_CONTINUE
    if row.get("multi_call_overflow") is True:
        return MODEL_PROTOCOL_INVALID, CELL_INVALID_CONTINUE

    if failure_class in SANDBOX_FAILURE_CLASSES:
        task_id = str(row.get("task_id") or "")
        declared = tuple((scripted_faults or {}).get(task_id, ()))
        if match_scripted_fault(row, declared).matched:
            return EXPECTED_SCRIPTED_FAULT, CONTINUE
        if failure_class == "invalid_resource":
            # The model addressed an identifier the sandbox could not resolve --
            # a modality/selection observation, not a sandbox malfunction.
            return MODEL_MODALITY_MISS, CELL_INVALID_CONTINUE
        # (K.2) FAIL CLOSED. A sandbox failure that cannot be bound to this task's
        # exact declared tool, resource and mode -- including one whose observed
        # provenance is missing altogether -- is unexplained, not designed.
        return UNEXPECTED_SANDBOX_FAILURE, CELL_INVALID_AND_HOLD

    # A malformed_response fault fires without a failure class, so recognise it
    # only against the task's own declaration.
    if row.get("fault_triggered") is True:
        task_id = str(row.get("task_id") or "")
        declared = tuple((scripted_faults or {}).get(task_id, ()))
        if match_scripted_fault(row, declared).matched:
            return EXPECTED_SCRIPTED_FAULT, CONTINUE
        # (K.2) FAIL CLOSED. A fault fired in the sandbox, and the row cannot
        # prove it was the declared one on the declared tool and resource.
        # ``fault_triggered`` alone establishes nothing.
        return UNEXPECTED_SANDBOX_FAILURE, CELL_INVALID_AND_HOLD

    if row.get("model_refusal") is True:
        return MODEL_REFUSAL, CONTINUE
    return CELL_OK, CONTINUE


# --------------------------------------------------------------------------
# Machine-enforced stop controller
# --------------------------------------------------------------------------


@dataclass(slots=True)
class ScheduleResult:
    terminal_status: str
    exit_code: int
    planned: int
    executed: int
    completed_rows: list[Mapping[str, Any]] = field(default_factory=list)
    classifications: list[dict[str, Any]] = field(default_factory=list)
    invalidated_cells: list[str] = field(default_factory=list)
    hold_reasons: list[str] = field(default_factory=list)
    stop_reason: str = ""
    stop_failure_class: str = ""
    stop_cell: str = ""
    stop_detail: list[str] = field(default_factory=list)
    not_started: list[str] = field(default_factory=list)

    @property
    def stopped(self) -> bool:
        return self.terminal_status == TERMINAL_STATUS_STOPPED


class ScheduleViolation(RuntimeError):
    """The caller tried to advance a schedule the controller had already stopped."""


class StopController:
    """Owns the frozen schedule so an immediate-stop condition cannot be ignored.

    The controller is deliberately the *iterator*. A caller cannot walk the
    schedule itself and forget to consult the stop state, because the only way to
    obtain the next cell is :meth:`cells`, which terminates the moment a stop is
    armed, and :meth:`record` raises if called after that point.
    """

    def __init__(
        self,
        schedule: Sequence[Cell],
        *,
        scripted_faults: Mapping[str, Sequence[ScriptedFault]] | None = None,
    ) -> None:
        self._schedule = tuple(schedule)
        self._faults = dict(scripted_faults or {})
        self._executed = 0
        self._stopped = False
        self._stop_reason = ""
        self._stop_failure_class = ""
        self._stop_cell = ""
        self._stop_detail: list[str] = []
        self._rows: list[Mapping[str, Any]] = []
        self._classifications: list[dict[str, Any]] = []
        self._invalidated: list[str] = []
        self._hold_reasons: list[str] = []
        self._seen: set[str] = set()

    # -- state ---------------------------------------------------------------

    @property
    def stopped(self) -> bool:
        return self._stopped

    @property
    def executed(self) -> int:
        return self._executed

    def remaining(self) -> list[str]:
        return [cell.key for cell in self._schedule[self._executed :]]

    # -- iteration -----------------------------------------------------------

    def cells(self) -> Iterator[Cell]:
        """Yield schedule positions, terminating immediately once stopped."""

        for cell in self._schedule:
            if self._stopped:
                return
            yield cell

    # -- recording -----------------------------------------------------------

    def record(self, cell: Cell, row: Mapping[str, Any]) -> str:
        """Bind, classify and update stop state. Returns the failure class."""

        if self._stopped:
            raise ScheduleViolation(
                f"cell {cell.key} was executed after the schedule stopped at "
                f"{self._stop_cell} ({self._stop_failure_class})"
            )
        # Schedule-order violations are protocol deviations, not identity drift.
        if cell.key in self._seen:
            self._arm_stop(cell, PROTOCOL_DEVIATION,
                           IMMEDIATE_STOP_RATIONALE[PROTOCOL_DEVIATION],
                           [f"cell {cell.key} was executed more than once"])
            return PROTOCOL_DEVIATION
        if cell.index != self._executed:
            self._arm_stop(cell, PROTOCOL_DEVIATION,
                           IMMEDIATE_STOP_RATIONALE[PROTOCOL_DEVIATION],
                           [f"cell {cell.key} ran at schedule position {self._executed}, "
                            f"frozen index is {cell.index}"])
            return PROTOCOL_DEVIATION

        self._seen.add(cell.key)
        self._rows.append(row)
        self._executed += 1

        # THE K.1 BINDING. The row must provably belong to this exact cell.
        mismatches = bind_row_to_cell(row, cell)
        if mismatches:
            self._classifications.append(
                {"cell": cell.key, "index": cell.index,
                 "failure_class": FROZEN_ARTIFACT_MISMATCH,
                 "disposition": IMMEDIATE_STOP, "detail": mismatches}
            )
            self._arm_stop(cell, FROZEN_ARTIFACT_MISMATCH,
                           IMMEDIATE_STOP_RATIONALE[FROZEN_ARTIFACT_MISMATCH], mismatches)
            return FROZEN_ARTIFACT_MISMATCH

        failure_class, disposition = classify_row(
            row, cell, scripted_faults=self._faults
        )
        self._classifications.append(
            {"cell": cell.key, "index": cell.index,
             "failure_class": failure_class, "disposition": disposition}
        )
        if disposition == IMMEDIATE_STOP:
            self._arm_stop(cell, failure_class,
                           IMMEDIATE_STOP_RATIONALE.get(failure_class, failure_class), [])
        elif disposition == CELL_INVALID_CONTINUE:
            self._invalidated.append(cell.key)
        elif disposition == CELL_INVALID_AND_HOLD:
            self._invalidated.append(cell.key)
            self._hold_reasons.append(f"{cell.key}: {failure_class}")
        elif disposition == VERDICT_HOLD_AFTER_COMPLETION:
            self._hold_reasons.append(f"{cell.key}: {failure_class}")
        return failure_class

    def _arm_stop(
        self, cell: Cell, failure_class: str, reason: str, detail: Sequence[str]
    ) -> None:
        self._stopped = True
        self._stop_cell = cell.key
        self._stop_failure_class = failure_class
        self._stop_reason = reason
        self._stop_detail = list(detail)

    # -- results -------------------------------------------------------------

    def result(self) -> ScheduleResult:
        if self._stopped:
            status, code = TERMINAL_STATUS_STOPPED, 3
        elif self._hold_reasons or self._invalidated:
            status, code = TERMINAL_STATUS_HOLD, 1
        else:
            status, code = TERMINAL_STATUS_OK, 0
        return ScheduleResult(
            terminal_status=status,
            exit_code=code,
            planned=len(self._schedule),
            executed=self._executed,
            completed_rows=list(self._rows),
            classifications=list(self._classifications),
            invalidated_cells=list(self._invalidated),
            hold_reasons=list(self._hold_reasons),
            stop_reason=self._stop_reason,
            stop_failure_class=self._stop_failure_class,
            stop_cell=self._stop_cell,
            stop_detail=list(self._stop_detail),
            not_started=self.remaining(),
        )

    def write_partial_manifest(self, path: Path) -> Path:
        """Persist the partial manifest a stopped schedule must leave behind."""

        result = self.result()
        payload = {
            "terminal_status": result.terminal_status,
            "exit_code": result.exit_code,
            "stopped": result.stopped,
            "planned_cells": result.planned,
            "executed_cells": result.executed,
            "stop_cell": result.stop_cell,
            "stop_failure_class": result.stop_failure_class,
            "stop_reason": result.stop_reason,
            "stop_detail": result.stop_detail,
            "invalidated_cells": result.invalidated_cells,
            "hold_reasons": result.hold_reasons,
            "cells_not_started": result.not_started,
            "classifications": result.classifications,
            "preserved_row_ids": [str(r.get("run_id") or "") for r in result.completed_rows],
            "note": (
                "Partial manifest written by the Phase-K stop controller. Every "
                "completed row is preserved exactly. No cell was retried, "
                "replaced or rerun."
            ),
        }
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(
            json.dumps(payload, indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
            newline="\n",
        )
        return path


def run_schedule(
    schedule: Sequence[Cell],
    execute: Callable[[Cell], Mapping[str, Any]],
    *,
    scripted_faults: Mapping[str, Sequence[ScriptedFault]] | None = None,
    partial_manifest_path: Path | None = None,
) -> ScheduleResult:
    """Drive a frozen schedule under machine-enforced stop semantics."""

    controller = StopController(schedule, scripted_faults=scripted_faults)
    for cell in controller.cells():
        row = execute(cell)
        controller.record(cell, row)
    if partial_manifest_path is not None:
        controller.write_partial_manifest(partial_manifest_path)
    return controller.result()


@dataclass(frozen=True, slots=True)
class ArmSpec:
    """One frozen arm: its name and the exact model identity it must run."""

    arm: str
    model: str
    model_digest: str


def build_schedule(
    arms: Sequence[ArmSpec],
    task_ids: Sequence[str],
    seeds: Sequence[int],
    *,
    qa_mode: str,
    benchmark_manifest_sha256: str,
) -> list[Cell]:
    """The frozen arm-major, task-major, seed-minor schedule.

    Every cell carries its complete expectation, so the binding check never has
    to consult a global mapping that cannot distinguish one arm from another.
    """

    cells: list[Cell] = []
    for spec in arms:
        for task_id in task_ids:
            for seed in seeds:
                cells.append(
                    Cell(
                        index=len(cells),
                        arm=spec.arm,
                        task_id=task_id,
                        seed=seed,
                        model=spec.model,
                        model_digest=spec.model_digest,
                        qa_mode=qa_mode,
                        benchmark_manifest_sha256=benchmark_manifest_sha256,
                    )
                )
    return cells
